/**
 * 
 */
package com.mindtree.service;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

import com.mindtree.service.ConvertNumber;

/**
 * @author Krithi
 *
 */
public class NumberToWordConverterTest {

	private Map<Integer,String> setup(){
		Map<Integer,String> numbers=new HashMap<>();
		numbers.put(0,"zero");
		numbers.put(1,"one");
		numbers.put(2,"two");
		numbers.put(3,"three");
		numbers.put(4,"four");
		numbers.put(5,"five");
		numbers.put(6,"six");
		numbers.put(7,"seven");
		numbers.put(8,"eight");
		numbers.put(9,"nine");
		numbers.put(10,"ten");
		numbers.put(11,"eleven");
		numbers.put(12,"twelve");
		numbers.put(13,"thirteen");
		numbers.put(14,"fourteen");
		numbers.put(15,"fifteen");
		numbers.put(16,"sixteen");
		numbers.put(17,"seventeen");
		numbers.put(18,"eighteen");
		numbers.put(19,"nineteen");
		numbers.put(20,"twenty");
		numbers.put(21,"twenty one");
		numbers.put(22,"twenty two");
		numbers.put(23,"twenty three");
		numbers.put(24,"twenty four");
		numbers.put(25,"twenty five");
		numbers.put(26,"twenty six");
		numbers.put(27,"twenty seven");
		numbers.put(28,"twenty eight");
		numbers.put(29,"twenty nine");
		numbers.put(30,"thirty");
		numbers.put(31,"thirty one");
		numbers.put(32,"thirty two");
		numbers.put(33,"thirty three");
		numbers.put(34,"thirty four");
		numbers.put(35,"thirty five");
		numbers.put(36,"thirty six");
		numbers.put(37,"thirty seven");
		numbers.put(38,"thirty eight");
		numbers.put(39,"thirty nine");
		numbers.put(40,"forty");
		numbers.put(41,"forty one");
		numbers.put(42,"forty two");
		numbers.put(43,"forty three");
		numbers.put(44,"forty four");
		numbers.put(45,"forty five");
		numbers.put(46,"forty six");
		numbers.put(47,"forty seven");
		numbers.put(48,"forty eight");
		numbers.put(49,"forty nine");
		numbers.put(50,"fifty");
		numbers.put(51,"fifty one");
		numbers.put(52,"fifty two");
		numbers.put(53,"fifty three");
		numbers.put(54,"fifty four");
		numbers.put(55,"fifty five");
		numbers.put(56,"fifty six");
		numbers.put(57,"fifty seven");
		numbers.put(58,"fifty eight");
		numbers.put(59,"fifty nine");
		numbers.put(60,"sixty");
		numbers.put(61,"sixty one");
		numbers.put(62,"sixty two");
		numbers.put(63,"sixty three");
		numbers.put(64,"sixty four");
		numbers.put(65,"sixty five");
		numbers.put(66,"sixty six");
		numbers.put(67,"sixty seven");
		numbers.put(68,"sixty eight");
		numbers.put(69,"sixty nine");
		numbers.put(70,"seventy");
		numbers.put(71,"seventy one");
		numbers.put(72,"seventy two");
		numbers.put(73,"seventy three");
		numbers.put(74,"seventy four");
		numbers.put(75,"seventy five");
		numbers.put(76,"seventy six");
		numbers.put(77,"seventy seven");
		numbers.put(78,"seventy eight");
		numbers.put(79,"seventy nine");
		numbers.put(80,"eighty");
		numbers.put(81,"eighty one");
		numbers.put(82,"eighty two");
		numbers.put(83,"eighty three");
		numbers.put(84,"eighty four");
		numbers.put(85,"eighty five");
		numbers.put(86,"eighty six");
		numbers.put(87,"eighty seven");
		numbers.put(88,"eighty eight");
		numbers.put(89,"eighty nine");
		numbers.put(90,"ninety");
		numbers.put(91,"ninety one");
		numbers.put(92,"ninety two");
		numbers.put(93,"ninety three");
		numbers.put(94,"ninety four");
		numbers.put(95,"ninety five");
		numbers.put(96,"ninety six");
		numbers.put(97,"ninety seven");
		numbers.put(98,"ninety eight");
		numbers.put(99,"ninety nine");
		numbers.put(100,"one hundred");
		numbers.put(101,"one hundred one");
		numbers.put(102,"one hundred two");
		numbers.put(103,"one hundred three");
		numbers.put(104,"one hundred four");
		numbers.put(105,"one hundred five");
		numbers.put(106,"one hundred six");
		numbers.put(107,"one hundred seven");
		numbers.put(108,"one hundred eight");
		numbers.put(109,"one hundred nine");
		numbers.put(110,"one hundred ten");
		numbers.put(111,"one hundred eleven");
		numbers.put(112,"one hundred twelve");
		numbers.put(113,"one hundred thirteen");
		numbers.put(114,"one hundred fourteen");
		numbers.put(115,"one hundred fifteen");
		numbers.put(116,"one hundred sixteen");
		numbers.put(117,"one hundred seventeen");
		numbers.put(118,"one hundred eighteen");
		numbers.put(119,"one hundred nineteen");
		numbers.put(120,"one hundred twenty");
		numbers.put(121,"one hundred twenty one");
		numbers.put(122,"one hundred twenty two");
		numbers.put(123,"one hundred twenty three");
		numbers.put(124,"one hundred twenty four");
		numbers.put(125,"one hundred twenty five");
		numbers.put(126,"one hundred twenty six");
		numbers.put(127,"one hundred twenty seven");
		numbers.put(128,"one hundred twenty eight");
		numbers.put(129,"one hundred twenty nine");
		numbers.put(130,"one hundred thirty");
		numbers.put(131,"one hundred thirty one");
		numbers.put(132,"one hundred thirty two");
		numbers.put(133,"one hundred thirty three");
		numbers.put(134,"one hundred thirty four");
		numbers.put(135,"one hundred thirty five");
		numbers.put(136,"one hundred thirty six");
		numbers.put(137,"one hundred thirty seven");
		numbers.put(138,"one hundred thirty eight");
		numbers.put(139,"one hundred thirty nine");
		numbers.put(140,"one hundred forty");
		numbers.put(141,"one hundred forty one");
		numbers.put(142,"one hundred forty two");
		numbers.put(143,"one hundred forty three");
		numbers.put(144,"one hundred forty four");
		numbers.put(145,"one hundred forty five");
		numbers.put(146,"one hundred forty six");
		numbers.put(147,"one hundred forty seven");
		numbers.put(148,"one hundred forty eight");
		numbers.put(149,"one hundred forty nine");
		numbers.put(150,"one hundred fifty");
		numbers.put(151,"one hundred fifty one");
		numbers.put(152,"one hundred fifty two");
		numbers.put(153,"one hundred fifty three");
		numbers.put(154,"one hundred fifty four");
		numbers.put(155,"one hundred fifty five");
		numbers.put(156,"one hundred fifty six");
		numbers.put(157,"one hundred fifty seven");
		numbers.put(158,"one hundred fifty eight");
		numbers.put(159,"one hundred fifty nine");
		numbers.put(160,"one hundred sixty");
		numbers.put(161,"one hundred sixty one");
		numbers.put(162,"one hundred sixty two");
		numbers.put(163,"one hundred sixty three");
		numbers.put(164,"one hundred sixty four");
		numbers.put(165,"one hundred sixty five");
		numbers.put(166,"one hundred sixty six");
		numbers.put(167,"one hundred sixty seven");
		numbers.put(168,"one hundred sixty eight");
		numbers.put(169,"one hundred sixty nine");
		numbers.put(170,"one hundred seventy");
		numbers.put(171,"one hundred seventy one");
		numbers.put(172,"one hundred seventy two");
		numbers.put(173,"one hundred seventy three");
		numbers.put(174,"one hundred seventy four");
		numbers.put(175,"one hundred seventy five");
		numbers.put(176,"one hundred seventy six");
		numbers.put(177,"one hundred seventy seven");
		numbers.put(178,"one hundred seventy eight");
		numbers.put(179,"one hundred seventy nine");
		numbers.put(180,"one hundred eighty");
		numbers.put(181,"one hundred eighty one");
		numbers.put(182,"one hundred eighty two");
		numbers.put(183,"one hundred eighty three");
		numbers.put(184,"one hundred eighty four");
		numbers.put(185,"one hundred eighty five");
		numbers.put(186,"one hundred eighty six");
		numbers.put(187,"one hundred eighty seven");
		numbers.put(188,"one hundred eighty eight");
		numbers.put(189,"one hundred eighty nine");
		numbers.put(190,"one hundred ninety");
		numbers.put(191,"one hundred ninety one");
		numbers.put(192,"one hundred ninety two");
		numbers.put(193,"one hundred ninety three");
		numbers.put(194,"one hundred ninety four");
		numbers.put(195,"one hundred ninety five");
		numbers.put(196,"one hundred ninety six");
		numbers.put(197,"one hundred ninety seven");
		numbers.put(198,"one hundred ninety eight");
		numbers.put(199,"one hundred ninety nine");
		numbers.put(200,"two hundred ");
		numbers.put(201,"two hundred one");
		numbers.put(202,"two hundred two");
		numbers.put(203,"two hundred three");
		numbers.put(204,"two hundred four");
		numbers.put(205,"two hundred five");
		numbers.put(206,"two hundred six");
		numbers.put(207,"two hundred seven");
		numbers.put(208,"two hundred eight");
		numbers.put(209,"two hundred nine");
		numbers.put(210,"two hundred ten");
		numbers.put(211,"two hundred eleven");
		numbers.put(212,"two hundred twelve");
		numbers.put(213,"two hundred thirteen");
		numbers.put(214,"two hundred fourteen");
		numbers.put(215,"two hundred fifteen");
		numbers.put(216,"two hundred sixteen");
		numbers.put(217,"two hundred seventeen");
		numbers.put(218,"two hundred eighteen");
		numbers.put(219,"two hundred nineteen");
		numbers.put(220,"two hundred twenty");
		numbers.put(221,"two hundred twenty one");
		numbers.put(222,"two hundred twenty two");
		numbers.put(223,"two hundred twenty three");
		numbers.put(224,"two hundred twenty four");
		numbers.put(225,"two hundred twenty five");
		numbers.put(226,"two hundred twenty six");
		numbers.put(227,"two hundred twenty seven");
		numbers.put(228,"two hundred twenty eight");
		numbers.put(229,"two hundred twenty nine");
		numbers.put(230,"two hundred thirty");
		numbers.put(231,"two hundred thirty one");
		numbers.put(232,"two hundred thirty two");
		numbers.put(233,"two hundred thirty three");
		numbers.put(234,"two hundred thirty four");
		numbers.put(235,"two hundred thirty five");
		numbers.put(236,"two hundred thirty six");
		numbers.put(237,"two hundred thirty seven");
		numbers.put(238,"two hundred thirty eight");
		numbers.put(239,"two hundred thirty nine");
		numbers.put(240,"two hundred forty");
		numbers.put(241,"two hundred forty one");
		numbers.put(242,"two hundred forty two");
		numbers.put(243,"two hundred forty three");
		numbers.put(244,"two hundred forty four");
		numbers.put(245,"two hundred forty five");
		numbers.put(246,"two hundred forty six");
		numbers.put(247,"two hundred forty seven");
		numbers.put(248,"two hundred forty eight");
		numbers.put(249,"two hundred forty nine");
		numbers.put(250,"two hundred fifty");
		numbers.put(251,"two hundred fifty one");
		numbers.put(252,"two hundred fifty two");
		numbers.put(253,"two hundred fifty three");
		numbers.put(254,"two hundred fifty four");
		numbers.put(255,"two hundred fifty five");
		numbers.put(256,"two hundred fifty six");
		numbers.put(257,"two hundred fifty seven");
		numbers.put(258,"two hundred fifty eight");
		numbers.put(259,"two hundred fifty nine");
		numbers.put(260,"two hundred sixty");
		numbers.put(261,"two hundred sixty one");
		numbers.put(262,"two hundred sixty two");
		numbers.put(263,"two hundred sixty three");
		numbers.put(264,"two hundred sixty four");
		numbers.put(265,"two hundred sixty five");
		numbers.put(266,"two hundred sixty six");
		numbers.put(267,"two hundred sixty seven");
		numbers.put(268,"two hundred sixty eight");
		numbers.put(269,"two hundred sixty nine");
		numbers.put(270,"two hundred seventy");
		numbers.put(271,"two hundred seventy one");
		numbers.put(272,"two hundred seventy two");
		numbers.put(273,"two hundred seventy three");
		numbers.put(274,"two hundred seventy four");
		numbers.put(275,"two hundred seventy five");
		numbers.put(276,"two hundred seventy six");
		numbers.put(277,"two hundred seventy seven");
		numbers.put(278,"two hundred seventy eight");
		numbers.put(279,"two hundred seventy nine");
		numbers.put(280,"two hundred eighty");
		numbers.put(281,"two hundred eighty one");
		numbers.put(282,"two hundred eighty two");
		numbers.put(283,"two hundred eighty three");
		numbers.put(284,"two hundred eighty four");
		numbers.put(285,"two hundred eighty five");
		numbers.put(286,"two hundred eighty six");
		numbers.put(287,"two hundred eighty seven");
		numbers.put(288,"two hundred eighty eight");
		numbers.put(289,"two hundred eighty nine");
		numbers.put(290,"two hundred ninety");
		numbers.put(291,"two hundred ninety one");
		numbers.put(292,"two hundred ninety two");
		numbers.put(293,"two hundred ninety three");
		numbers.put(294,"two hundred ninety four");
		numbers.put(295,"two hundred ninety five");
		numbers.put(296,"two hundred ninety six");
		numbers.put(297,"two hundred ninety seven");
		numbers.put(298,"two hundred ninety eight");
		numbers.put(299,"two hundred ninety nine");
		numbers.put(300,"three hundred ");
		numbers.put(301,"three hundred one");
		numbers.put(302,"three hundred two");
		numbers.put(303,"three hundred three");
		numbers.put(304,"three hundred four");
		numbers.put(305,"three hundred five");
		numbers.put(306,"three hundred six");
		numbers.put(307,"three hundred seven");
		numbers.put(308,"three hundred eight");
		numbers.put(309,"three hundred nine");
		numbers.put(310,"three hundred ten");
		numbers.put(311,"three hundred eleven");
		numbers.put(312,"three hundred twelve");
		numbers.put(313,"three hundred thirteen");
		numbers.put(314,"three hundred fourteen");
		numbers.put(315,"three hundred fifteen");
		numbers.put(316,"three hundred sixteen");
		numbers.put(317,"three hundred seventeen");
		numbers.put(318,"three hundred eighteen");
		numbers.put(319,"three hundred nineteen");
		numbers.put(320,"three hundred twenty");
		numbers.put(321,"three hundred twenty one");
		numbers.put(322,"three hundred twenty two");
		numbers.put(323,"three hundred twenty three");
		numbers.put(324,"three hundred twenty four");
		numbers.put(325,"three hundred twenty five");
		numbers.put(326,"three hundred twenty six");
		numbers.put(327,"three hundred twenty seven");
		numbers.put(328,"three hundred twenty eight");
		numbers.put(329,"three hundred twenty nine");
		numbers.put(330,"three hundred thirty");
		numbers.put(331,"three hundred thirty one");
		numbers.put(332,"three hundred thirty two");
		numbers.put(333,"three hundred thirty three");
		numbers.put(334,"three hundred thirty four");
		numbers.put(335,"three hundred thirty five");
		numbers.put(336,"three hundred thirty six");
		numbers.put(337,"three hundred thirty seven");
		numbers.put(338,"three hundred thirty eight");
		numbers.put(339,"three hundred thirty nine");
		numbers.put(340,"three hundred forty");
		numbers.put(341,"three hundred forty one");
		numbers.put(342,"three hundred forty two");
		numbers.put(343,"three hundred forty three");
		numbers.put(344,"three hundred forty four");
		numbers.put(345,"three hundred forty five");
		numbers.put(346,"three hundred forty six");
		numbers.put(347,"three hundred forty seven");
		numbers.put(348,"three hundred forty eight");
		numbers.put(349,"three hundred forty nine");
		numbers.put(350,"three hundred fifty");
		numbers.put(351,"three hundred fifty one");
		numbers.put(352,"three hundred fifty two");
		numbers.put(353,"three hundred fifty three");
		numbers.put(354,"three hundred fifty four");
		numbers.put(355,"three hundred fifty five");
		numbers.put(356,"three hundred fifty six");
		numbers.put(357,"three hundred fifty seven");
		numbers.put(358,"three hundred fifty eight");
		numbers.put(359,"three hundred fifty nine");
		numbers.put(360,"three hundred sixty");
		numbers.put(361,"three hundred sixty one");
		numbers.put(362,"three hundred sixty two");
		numbers.put(363,"three hundred sixty three");
		numbers.put(364,"three hundred sixty four");
		numbers.put(365,"three hundred sixty five");
		numbers.put(366,"three hundred sixty six");
		numbers.put(367,"three hundred sixty seven");
		numbers.put(368,"three hundred sixty eight");
		numbers.put(369,"three hundred sixty nine");
		numbers.put(370,"three hundred seventy");
		numbers.put(371,"three hundred seventy one");
		numbers.put(372,"three hundred seventy two");
		numbers.put(373,"three hundred seventy three");
		numbers.put(374,"three hundred seventy four");
		numbers.put(375,"three hundred seventy five");
		numbers.put(376,"three hundred seventy six");
		numbers.put(377,"three hundred seventy seven");
		numbers.put(378,"three hundred seventy eight");
		numbers.put(379,"three hundred seventy nine");
		numbers.put(380,"three hundred eighty");
		numbers.put(381,"three hundred eighty one");
		numbers.put(382,"three hundred eighty two");
		numbers.put(383,"three hundred eighty three");
		numbers.put(384,"three hundred eighty four");
		numbers.put(385,"three hundred eighty five");
		numbers.put(386,"three hundred eighty six");
		numbers.put(387,"three hundred eighty seven");
		numbers.put(388,"three hundred eighty eight");
		numbers.put(389,"three hundred eighty nine");
		numbers.put(390,"three hundred ninety");
		numbers.put(391,"three hundred ninety one");
		numbers.put(392,"three hundred ninety two");
		numbers.put(393,"three hundred ninety three");
		numbers.put(394,"three hundred ninety four");
		numbers.put(395,"three hundred ninety five");
		numbers.put(396,"three hundred ninety six");
		numbers.put(397,"three hundred ninety seven");
		numbers.put(398,"three hundred ninety eight");
		numbers.put(399,"three hundred ninety nine");
		numbers.put(400,"four hundred ");
		numbers.put(401,"four hundred one");
		numbers.put(402,"four hundred two");
		numbers.put(403,"four hundred three");
		numbers.put(404,"four hundred four");
		numbers.put(405,"four hundred five");
		numbers.put(406,"four hundred six");
		numbers.put(407,"four hundred seven");
		numbers.put(408,"four hundred eight");
		numbers.put(409,"four hundred nine");
		numbers.put(410,"four hundred ten");
		numbers.put(411,"four hundred eleven");
		numbers.put(412,"four hundred twelve");
		numbers.put(413,"four hundred thirteen");
		numbers.put(414,"four hundred fourteen");
		numbers.put(415,"four hundred fifteen");
		numbers.put(416,"four hundred sixteen");
		numbers.put(417,"four hundred seventeen");
		numbers.put(418,"four hundred eighteen");
		numbers.put(419,"four hundred nineteen");
		numbers.put(420,"four hundred twenty");
		numbers.put(421,"four hundred twenty one");
		numbers.put(422,"four hundred twenty two");
		numbers.put(423,"four hundred twenty three");
		numbers.put(424,"four hundred twenty four");
		numbers.put(425,"four hundred twenty five");
		numbers.put(426,"four hundred twenty six");
		numbers.put(427,"four hundred twenty seven");
		numbers.put(428,"four hundred twenty eight");
		numbers.put(429,"four hundred twenty nine");
		numbers.put(430,"four hundred thirty");
		numbers.put(431,"four hundred thirty one");
		numbers.put(432,"four hundred thirty two");
		numbers.put(433,"four hundred thirty three");
		numbers.put(434,"four hundred thirty four");
		numbers.put(435,"four hundred thirty five");
		numbers.put(436,"four hundred thirty six");
		numbers.put(437,"four hundred thirty seven");
		numbers.put(438,"four hundred thirty eight");
		numbers.put(439,"four hundred thirty nine");
		numbers.put(440,"four hundred forty");
		numbers.put(441,"four hundred forty one");
		numbers.put(442,"four hundred forty two");
		numbers.put(443,"four hundred forty three");
		numbers.put(444,"four hundred forty four");
		numbers.put(445,"four hundred forty five");
		numbers.put(446,"four hundred forty six");
		numbers.put(447,"four hundred forty seven");
		numbers.put(448,"four hundred forty eight");
		numbers.put(449,"four hundred forty nine");
		numbers.put(450,"four hundred fifty");
		numbers.put(451,"four hundred fifty one");
		numbers.put(452,"four hundred fifty two");
		numbers.put(453,"four hundred fifty three");
		numbers.put(454,"four hundred fifty four");
		numbers.put(455,"four hundred fifty five");
		numbers.put(456,"four hundred fifty six");
		numbers.put(457,"four hundred fifty seven");
		numbers.put(458,"four hundred fifty eight");
		numbers.put(459,"four hundred fifty nine");
		numbers.put(460,"four hundred sixty");
		numbers.put(461,"four hundred sixty one");
		numbers.put(462,"four hundred sixty two");
		numbers.put(463,"four hundred sixty three");
		numbers.put(464,"four hundred sixty four");
		numbers.put(465,"four hundred sixty five");
		numbers.put(466,"four hundred sixty six");
		numbers.put(467,"four hundred sixty seven");
		numbers.put(468,"four hundred sixty eight");
		numbers.put(469,"four hundred sixty nine");
		numbers.put(470,"four hundred seventy");
		numbers.put(471,"four hundred seventy one");
		numbers.put(472,"four hundred seventy two");
		numbers.put(473,"four hundred seventy three");
		numbers.put(474,"four hundred seventy four");
		numbers.put(475,"four hundred seventy five");
		numbers.put(476,"four hundred seventy six");
		numbers.put(477,"four hundred seventy seven");
		numbers.put(478,"four hundred seventy eight");
		numbers.put(479,"four hundred seventy nine");
		numbers.put(480,"four hundred eighty");
		numbers.put(481,"four hundred eighty one");
		numbers.put(482,"four hundred eighty two");
		numbers.put(483,"four hundred eighty three");
		numbers.put(484,"four hundred eighty four");
		numbers.put(485,"four hundred eighty five");
		numbers.put(486,"four hundred eighty six");
		numbers.put(487,"four hundred eighty seven");
		numbers.put(488,"four hundred eighty eight");
		numbers.put(489,"four hundred eighty nine");
		numbers.put(490,"four hundred ninety");
		numbers.put(491,"four hundred ninety one");
		numbers.put(492,"four hundred ninety two");
		numbers.put(493,"four hundred ninety three");
		numbers.put(494,"four hundred ninety four");
		numbers.put(495,"four hundred ninety five");
		numbers.put(496,"four hundred ninety six");
		numbers.put(497,"four hundred ninety seven");
		numbers.put(498,"four hundred ninety eight");
		numbers.put(499,"four hundred ninety nine");
		numbers.put(500,"five hundred ");
		numbers.put(501,"five hundred one");
		numbers.put(502,"five hundred two");
		numbers.put(503,"five hundred three");
		numbers.put(504,"five hundred four");
		numbers.put(505,"five hundred five");
		numbers.put(506,"five hundred six");
		numbers.put(507,"five hundred seven");
		numbers.put(508,"five hundred eight");
		numbers.put(509,"five hundred nine");
		numbers.put(510,"five hundred ten");
		numbers.put(511,"five hundred eleven");
		numbers.put(512,"five hundred twelve");
		numbers.put(513,"five hundred thirteen");
		numbers.put(514,"five hundred fourteen");
		numbers.put(515,"five hundred fifteen");
		numbers.put(516,"five hundred sixteen");
		numbers.put(517,"five hundred seventeen");
		numbers.put(518,"five hundred eighteen");
		numbers.put(519,"five hundred nineteen");
		numbers.put(520,"five hundred twenty");
		numbers.put(521,"five hundred twenty one");
		numbers.put(522,"five hundred twenty two");
		numbers.put(523,"five hundred twenty three");
		numbers.put(524,"five hundred twenty four");
		numbers.put(525,"five hundred twenty five");
		numbers.put(526,"five hundred twenty six");
		numbers.put(527,"five hundred twenty seven");
		numbers.put(528,"five hundred twenty eight");
		numbers.put(529,"five hundred twenty nine");
		numbers.put(530,"five hundred thirty");
		numbers.put(531,"five hundred thirty one");
		numbers.put(532,"five hundred thirty two");
		numbers.put(533,"five hundred thirty three");
		numbers.put(534,"five hundred thirty four");
		numbers.put(535,"five hundred thirty five");
		numbers.put(536,"five hundred thirty six");
		numbers.put(537,"five hundred thirty seven");
		numbers.put(538,"five hundred thirty eight");
		numbers.put(539,"five hundred thirty nine");
		numbers.put(540,"five hundred forty");
		numbers.put(541,"five hundred forty one");
		numbers.put(542,"five hundred forty two");
		numbers.put(543,"five hundred forty three");
		numbers.put(544,"five hundred forty four");
		numbers.put(545,"five hundred forty five");
		numbers.put(546,"five hundred forty six");
		numbers.put(547,"five hundred forty seven");
		numbers.put(548,"five hundred forty eight");
		numbers.put(549,"five hundred forty nine");
		numbers.put(550,"five hundred fifty");
		numbers.put(551,"five hundred fifty one");
		numbers.put(552,"five hundred fifty two");
		numbers.put(553,"five hundred fifty three");
		numbers.put(554,"five hundred fifty four");
		numbers.put(555,"five hundred fifty five");
		numbers.put(556,"five hundred fifty six");
		numbers.put(557,"five hundred fifty seven");
		numbers.put(558,"five hundred fifty eight");
		numbers.put(559,"five hundred fifty nine");
		numbers.put(560,"five hundred sixty");
		numbers.put(561,"five hundred sixty one");
		numbers.put(562,"five hundred sixty two");
		numbers.put(563,"five hundred sixty three");
		numbers.put(564,"five hundred sixty four");
		numbers.put(565,"five hundred sixty five");
		numbers.put(566,"five hundred sixty six");
		numbers.put(567,"five hundred sixty seven");
		numbers.put(568,"five hundred sixty eight");
		numbers.put(569,"five hundred sixty nine");
		numbers.put(570,"five hundred seventy");
		numbers.put(571,"five hundred seventy one");
		numbers.put(572,"five hundred seventy two");
		numbers.put(573,"five hundred seventy three");
		numbers.put(574,"five hundred seventy four");
		numbers.put(575,"five hundred seventy five");
		numbers.put(576,"five hundred seventy six");
		numbers.put(577,"five hundred seventy seven");
		numbers.put(578,"five hundred seventy eight");
		numbers.put(579,"five hundred seventy nine");
		numbers.put(580,"five hundred eighty");
		numbers.put(581,"five hundred eighty one");
		numbers.put(582,"five hundred eighty two");
		numbers.put(583,"five hundred eighty three");
		numbers.put(584,"five hundred eighty four");
		numbers.put(585,"five hundred eighty five");
		numbers.put(586,"five hundred eighty six");
		numbers.put(587,"five hundred eighty seven");
		numbers.put(588,"five hundred eighty eight");
		numbers.put(589,"five hundred eighty nine");
		numbers.put(590,"five hundred ninety");
		numbers.put(591,"five hundred ninety one");
		numbers.put(592,"five hundred ninety two");
		numbers.put(593,"five hundred ninety three");
		numbers.put(594,"five hundred ninety four");
		numbers.put(595,"five hundred ninety five");
		numbers.put(596,"five hundred ninety six");
		numbers.put(597,"five hundred ninety seven");
		numbers.put(598,"five hundred ninety eight");
		numbers.put(599,"five hundred ninety nine");
		numbers.put(600,"six hundred ");
		numbers.put(601,"six hundred one");
		numbers.put(602,"six hundred two");
		numbers.put(603,"six hundred three");
		numbers.put(604,"six hundred four");
		numbers.put(605,"six hundred five");
		numbers.put(606,"six hundred six");
		numbers.put(607,"six hundred seven");
		numbers.put(608,"six hundred eight");
		numbers.put(609,"six hundred nine");
		numbers.put(610,"six hundred ten");
		numbers.put(611,"six hundred eleven");
		numbers.put(612,"six hundred twelve");
		numbers.put(613,"six hundred thirteen");
		numbers.put(614,"six hundred fourteen");
		numbers.put(615,"six hundred fifteen");
		numbers.put(616,"six hundred sixteen");
		numbers.put(617,"six hundred seventeen");
		numbers.put(618,"six hundred eighteen");
		numbers.put(619,"six hundred nineteen");
		numbers.put(620,"six hundred twenty");
		numbers.put(621,"six hundred twenty one");
		numbers.put(622,"six hundred twenty two");
		numbers.put(623,"six hundred twenty three");
		numbers.put(624,"six hundred twenty four");
		numbers.put(625,"six hundred twenty five");
		numbers.put(626,"six hundred twenty six");
		numbers.put(627,"six hundred twenty seven");
		numbers.put(628,"six hundred twenty eight");
		numbers.put(629,"six hundred twenty nine");
		numbers.put(630,"six hundred thirty");
		numbers.put(631,"six hundred thirty one");
		numbers.put(632,"six hundred thirty two");
		numbers.put(633,"six hundred thirty three");
		numbers.put(634,"six hundred thirty four");
		numbers.put(635,"six hundred thirty five");
		numbers.put(636,"six hundred thirty six");
		numbers.put(637,"six hundred thirty seven");
		numbers.put(638,"six hundred thirty eight");
		numbers.put(639,"six hundred thirty nine");
		numbers.put(640,"six hundred forty");
		numbers.put(641,"six hundred forty one");
		numbers.put(642,"six hundred forty two");
		numbers.put(643,"six hundred forty three");
		numbers.put(644,"six hundred forty four");
		numbers.put(645,"six hundred forty five");
		numbers.put(646,"six hundred forty six");
		numbers.put(647,"six hundred forty seven");
		numbers.put(648,"six hundred forty eight");
		numbers.put(649,"six hundred forty nine");
		numbers.put(650,"six hundred fifty");
		numbers.put(651,"six hundred fifty one");
		numbers.put(652,"six hundred fifty two");
		numbers.put(653,"six hundred fifty three");
		numbers.put(654,"six hundred fifty four");
		numbers.put(655,"six hundred fifty five");
		numbers.put(656,"six hundred fifty six");
		numbers.put(657,"six hundred fifty seven");
		numbers.put(658,"six hundred fifty eight");
		numbers.put(659,"six hundred fifty nine");
		numbers.put(660,"six hundred sixty");
		numbers.put(661,"six hundred sixty one");
		numbers.put(662,"six hundred sixty two");
		numbers.put(663,"six hundred sixty three");
		numbers.put(664,"six hundred sixty four");
		numbers.put(665,"six hundred sixty five");
		numbers.put(666,"six hundred sixty six");
		numbers.put(667,"six hundred sixty seven");
		numbers.put(668,"six hundred sixty eight");
		numbers.put(669,"six hundred sixty nine");
		numbers.put(670,"six hundred seventy");
		numbers.put(671,"six hundred seventy one");
		numbers.put(672,"six hundred seventy two");
		numbers.put(673,"six hundred seventy three");
		numbers.put(674,"six hundred seventy four");
		numbers.put(675,"six hundred seventy five");
		numbers.put(676,"six hundred seventy six");
		numbers.put(677,"six hundred seventy seven");
		numbers.put(678,"six hundred seventy eight");
		numbers.put(679,"six hundred seventy nine");
		numbers.put(680,"six hundred eighty");
		numbers.put(681,"six hundred eighty one");
		numbers.put(682,"six hundred eighty two");
		numbers.put(683,"six hundred eighty three");
		numbers.put(684,"six hundred eighty four");
		numbers.put(685,"six hundred eighty five");
		numbers.put(686,"six hundred eighty six");
		numbers.put(687,"six hundred eighty seven");
		numbers.put(688,"six hundred eighty eight");
		numbers.put(689,"six hundred eighty nine");
		numbers.put(690,"six hundred ninety");
		numbers.put(691,"six hundred ninety one");
		numbers.put(692,"six hundred ninety two");
		numbers.put(693,"six hundred ninety three");
		numbers.put(694,"six hundred ninety four");
		numbers.put(695,"six hundred ninety five");
		numbers.put(696,"six hundred ninety six");
		numbers.put(697,"six hundred ninety seven");
		numbers.put(698,"six hundred ninety eight");
		numbers.put(699,"six hundred ninety nine");
		numbers.put(700,"seven hundred ");
		numbers.put(701,"seven hundred one");
		numbers.put(702,"seven hundred two");
		numbers.put(703,"seven hundred three");
		numbers.put(704,"seven hundred four");
		numbers.put(705,"seven hundred five");
		numbers.put(706,"seven hundred six");
		numbers.put(707,"seven hundred seven");
		numbers.put(708,"seven hundred eight");
		numbers.put(709,"seven hundred nine");
		numbers.put(710,"seven hundred ten");
		numbers.put(711,"seven hundred eleven");
		numbers.put(712,"seven hundred twelve");
		numbers.put(713,"seven hundred thirteen");
		numbers.put(714,"seven hundred fourteen");
		numbers.put(715,"seven hundred fifteen");
		numbers.put(716,"seven hundred sixteen");
		numbers.put(717,"seven hundred seventeen");
		numbers.put(718,"seven hundred eighteen");
		numbers.put(719,"seven hundred nineteen");
		numbers.put(720,"seven hundred twenty");
		numbers.put(721,"seven hundred twenty one");
		numbers.put(722,"seven hundred twenty two");
		numbers.put(723,"seven hundred twenty three");
		numbers.put(724,"seven hundred twenty four");
		numbers.put(725,"seven hundred twenty five");
		numbers.put(726,"seven hundred twenty six");
		numbers.put(727,"seven hundred twenty seven");
		numbers.put(728,"seven hundred twenty eight");
		numbers.put(729,"seven hundred twenty nine");
		numbers.put(730,"seven hundred thirty");
		numbers.put(731,"seven hundred thirty one");
		numbers.put(732,"seven hundred thirty two");
		numbers.put(733,"seven hundred thirty three");
		numbers.put(734,"seven hundred thirty four");
		numbers.put(735,"seven hundred thirty five");
		numbers.put(736,"seven hundred thirty six");
		numbers.put(737,"seven hundred thirty seven");
		numbers.put(738,"seven hundred thirty eight");
		numbers.put(739,"seven hundred thirty nine");
		numbers.put(740,"seven hundred forty");
		numbers.put(741,"seven hundred forty one");
		numbers.put(742,"seven hundred forty two");
		numbers.put(743,"seven hundred forty three");
		numbers.put(744,"seven hundred forty four");
		numbers.put(745,"seven hundred forty five");
		numbers.put(746,"seven hundred forty six");
		numbers.put(747,"seven hundred forty seven");
		numbers.put(748,"seven hundred forty eight");
		numbers.put(749,"seven hundred forty nine");
		numbers.put(750,"seven hundred fifty");
		numbers.put(751,"seven hundred fifty one");
		numbers.put(752,"seven hundred fifty two");
		numbers.put(753,"seven hundred fifty three");
		numbers.put(754,"seven hundred fifty four");
		numbers.put(755,"seven hundred fifty five");
		numbers.put(756,"seven hundred fifty six");
		numbers.put(757,"seven hundred fifty seven");
		numbers.put(758,"seven hundred fifty eight");
		numbers.put(759,"seven hundred fifty nine");
		numbers.put(760,"seven hundred sixty");
		numbers.put(761,"seven hundred sixty one");
		numbers.put(762,"seven hundred sixty two");
		numbers.put(763,"seven hundred sixty three");
		numbers.put(764,"seven hundred sixty four");
		numbers.put(765,"seven hundred sixty five");
		numbers.put(766,"seven hundred sixty six");
		numbers.put(767,"seven hundred sixty seven");
		numbers.put(768,"seven hundred sixty eight");
		numbers.put(769,"seven hundred sixty nine");
		numbers.put(770,"seven hundred seventy");
		numbers.put(771,"seven hundred seventy one");
		numbers.put(772,"seven hundred seventy two");
		numbers.put(773,"seven hundred seventy three");
		numbers.put(774,"seven hundred seventy four");
		numbers.put(775,"seven hundred seventy five");
		numbers.put(776,"seven hundred seventy six");
		numbers.put(777,"seven hundred seventy seven");
		numbers.put(778,"seven hundred seventy eight");
		numbers.put(779,"seven hundred seventy nine");
		numbers.put(780,"seven hundred eighty");
		numbers.put(781,"seven hundred eighty one");
		numbers.put(782,"seven hundred eighty two");
		numbers.put(783,"seven hundred eighty three");
		numbers.put(784,"seven hundred eighty four");
		numbers.put(785,"seven hundred eighty five");
		numbers.put(786,"seven hundred eighty six");
		numbers.put(787,"seven hundred eighty seven");
		numbers.put(788,"seven hundred eighty eight");
		numbers.put(789,"seven hundred eighty nine");
		numbers.put(790,"seven hundred ninety");
		numbers.put(791,"seven hundred ninety one");
		numbers.put(792,"seven hundred ninety two");
		numbers.put(793,"seven hundred ninety three");
		numbers.put(794,"seven hundred ninety four");
		numbers.put(795,"seven hundred ninety five");
		numbers.put(796,"seven hundred ninety six");
		numbers.put(797,"seven hundred ninety seven");
		numbers.put(798,"seven hundred ninety eight");
		numbers.put(799,"seven hundred ninety nine");
		numbers.put(800,"eight hundred ");
		numbers.put(801,"eight hundred one");
		numbers.put(802,"eight hundred two");
		numbers.put(803,"eight hundred three");
		numbers.put(804,"eight hundred four");
		numbers.put(805,"eight hundred five");
		numbers.put(806,"eight hundred six");
		numbers.put(807,"eight hundred seven");
		numbers.put(808,"eight hundred eight");
		numbers.put(809,"eight hundred nine");
		numbers.put(810,"eight hundred ten");
		numbers.put(811,"eight hundred eleven");
		numbers.put(812,"eight hundred twelve");
		numbers.put(813,"eight hundred thirteen");
		numbers.put(814,"eight hundred fourteen");
		numbers.put(815,"eight hundred fifteen");
		numbers.put(816,"eight hundred sixteen");
		numbers.put(817,"eight hundred seventeen");
		numbers.put(818,"eight hundred eighteen");
		numbers.put(819,"eight hundred nineteen");
		numbers.put(820,"eight hundred twenty");
		numbers.put(821,"eight hundred twenty one");
		numbers.put(822,"eight hundred twenty two");
		numbers.put(823,"eight hundred twenty three");
		numbers.put(824,"eight hundred twenty four");
		numbers.put(825,"eight hundred twenty five");
		numbers.put(826,"eight hundred twenty six");
		numbers.put(827,"eight hundred twenty seven");
		numbers.put(828,"eight hundred twenty eight");
		numbers.put(829,"eight hundred twenty nine");
		numbers.put(830,"eight hundred thirty");
		numbers.put(831,"eight hundred thirty one");
		numbers.put(832,"eight hundred thirty two");
		numbers.put(833,"eight hundred thirty three");
		numbers.put(834,"eight hundred thirty four");
		numbers.put(835,"eight hundred thirty five");
		numbers.put(836,"eight hundred thirty six");
		numbers.put(837,"eight hundred thirty seven");
		numbers.put(838,"eight hundred thirty eight");
		numbers.put(839,"eight hundred thirty nine");
		numbers.put(840,"eight hundred forty");
		numbers.put(841,"eight hundred forty one");
		numbers.put(842,"eight hundred forty two");
		numbers.put(843,"eight hundred forty three");
		numbers.put(844,"eight hundred forty four");
		numbers.put(845,"eight hundred forty five");
		numbers.put(846,"eight hundred forty six");
		numbers.put(847,"eight hundred forty seven");
		numbers.put(848,"eight hundred forty eight");
		numbers.put(849,"eight hundred forty nine");
		numbers.put(850,"eight hundred fifty");
		numbers.put(851,"eight hundred fifty one");
		numbers.put(852,"eight hundred fifty two");
		numbers.put(853,"eight hundred fifty three");
		numbers.put(854,"eight hundred fifty four");
		numbers.put(855,"eight hundred fifty five");
		numbers.put(856,"eight hundred fifty six");
		numbers.put(857,"eight hundred fifty seven");
		numbers.put(858,"eight hundred fifty eight");
		numbers.put(859,"eight hundred fifty nine");
		numbers.put(860,"eight hundred sixty");
		numbers.put(861,"eight hundred sixty one");
		numbers.put(862,"eight hundred sixty two");
		numbers.put(863,"eight hundred sixty three");
		numbers.put(864,"eight hundred sixty four");
		numbers.put(865,"eight hundred sixty five");
		numbers.put(866,"eight hundred sixty six");
		numbers.put(867,"eight hundred sixty seven");
		numbers.put(868,"eight hundred sixty eight");
		numbers.put(869,"eight hundred sixty nine");
		numbers.put(870,"eight hundred seventy");
		numbers.put(871,"eight hundred seventy one");
		numbers.put(872,"eight hundred seventy two");
		numbers.put(873,"eight hundred seventy three");
		numbers.put(874,"eight hundred seventy four");
		numbers.put(875,"eight hundred seventy five");
		numbers.put(876,"eight hundred seventy six");
		numbers.put(877,"eight hundred seventy seven");
		numbers.put(878,"eight hundred seventy eight");
		numbers.put(879,"eight hundred seventy nine");
		numbers.put(880,"eight hundred eighty");
		numbers.put(881,"eight hundred eighty one");
		numbers.put(882,"eight hundred eighty two");
		numbers.put(883,"eight hundred eighty three");
		numbers.put(884,"eight hundred eighty four");
		numbers.put(885,"eight hundred eighty five");
		numbers.put(886,"eight hundred eighty six");
		numbers.put(887,"eight hundred eighty seven");
		numbers.put(888,"eight hundred eighty eight");
		numbers.put(889,"eight hundred eighty nine");
		numbers.put(890,"eight hundred ninety");
		numbers.put(891,"eight hundred ninety one");
		numbers.put(892,"eight hundred ninety two");
		numbers.put(893,"eight hundred ninety three");
		numbers.put(894,"eight hundred ninety four");
		numbers.put(895,"eight hundred ninety five");
		numbers.put(896,"eight hundred ninety six");
		numbers.put(897,"eight hundred ninety seven");
		numbers.put(898,"eight hundred ninety eight");
		numbers.put(899,"eight hundred ninety nine");
		numbers.put(900,"nine hundred ");
		numbers.put(901,"nine hundred one");
		numbers.put(902,"nine hundred two");
		numbers.put(903,"nine hundred three");
		numbers.put(904,"nine hundred four");
		numbers.put(905,"nine hundred five");
		numbers.put(906,"nine hundred six");
		numbers.put(907,"nine hundred seven");
		numbers.put(908,"nine hundred eight");
		numbers.put(909,"nine hundred nine");
		numbers.put(910,"nine hundred ten");
		numbers.put(911,"nine hundred eleven");
		numbers.put(912,"nine hundred twelve");
		numbers.put(913,"nine hundred thirteen");
		numbers.put(914,"nine hundred fourteen");
		numbers.put(915,"nine hundred fifteen");
		numbers.put(916,"nine hundred sixteen");
		numbers.put(917,"nine hundred seventeen");
		numbers.put(918,"nine hundred eighteen");
		numbers.put(919,"nine hundred nineteen");
		numbers.put(920,"nine hundred twenty");
		numbers.put(921,"nine hundred twenty one");
		numbers.put(922,"nine hundred twenty two");
		numbers.put(923,"nine hundred twenty three");
		numbers.put(924,"nine hundred twenty four");
		numbers.put(925,"nine hundred twenty five");
		numbers.put(926,"nine hundred twenty six");
		numbers.put(927,"nine hundred twenty seven");
		numbers.put(928,"nine hundred twenty eight");
		numbers.put(929,"nine hundred twenty nine");
		numbers.put(930,"nine hundred thirty");
		numbers.put(931,"nine hundred thirty one");
		numbers.put(932,"nine hundred thirty two");
		numbers.put(933,"nine hundred thirty three");
		numbers.put(934,"nine hundred thirty four");
		numbers.put(935,"nine hundred thirty five");
		numbers.put(936,"nine hundred thirty six");
		numbers.put(937,"nine hundred thirty seven");
		numbers.put(938,"nine hundred thirty eight");
		numbers.put(939,"nine hundred thirty nine");
		numbers.put(940,"nine hundred forty");
		numbers.put(941,"nine hundred forty one");
		numbers.put(942,"nine hundred forty two");
		numbers.put(943,"nine hundred forty three");
		numbers.put(944,"nine hundred forty four");
		numbers.put(945,"nine hundred forty five");
		numbers.put(946,"nine hundred forty six");
		numbers.put(947,"nine hundred forty seven");
		numbers.put(948,"nine hundred forty eight");
		numbers.put(949,"nine hundred forty nine");
		numbers.put(950,"nine hundred fifty");
		numbers.put(951,"nine hundred fifty one");
		numbers.put(952,"nine hundred fifty two");
		numbers.put(953,"nine hundred fifty three");
		numbers.put(954,"nine hundred fifty four");
		numbers.put(955,"nine hundred fifty five");
		numbers.put(956,"nine hundred fifty six");
		numbers.put(957,"nine hundred fifty seven");
		numbers.put(958,"nine hundred fifty eight");
		numbers.put(959,"nine hundred fifty nine");
		numbers.put(960,"nine hundred sixty");
		numbers.put(961,"nine hundred sixty one");
		numbers.put(962,"nine hundred sixty two");
		numbers.put(963,"nine hundred sixty three");
		numbers.put(964,"nine hundred sixty four");
		numbers.put(965,"nine hundred sixty five");
		numbers.put(966,"nine hundred sixty six");
		numbers.put(967,"nine hundred sixty seven");
		numbers.put(968,"nine hundred sixty eight");
		numbers.put(969,"nine hundred sixty nine");
		numbers.put(970,"nine hundred seventy");
		numbers.put(971,"nine hundred seventy one");
		numbers.put(972,"nine hundred seventy two");
		numbers.put(973,"nine hundred seventy three");
		numbers.put(974,"nine hundred seventy four");
		numbers.put(975,"nine hundred seventy five");
		numbers.put(976,"nine hundred seventy six");
		numbers.put(977,"nine hundred seventy seven");
		numbers.put(978,"nine hundred seventy eight");
		numbers.put(979,"nine hundred seventy nine");
		numbers.put(980,"nine hundred eighty");
		numbers.put(981,"nine hundred eighty one");
		numbers.put(982,"nine hundred eighty two");
		numbers.put(983,"nine hundred eighty three");
		numbers.put(984,"nine hundred eighty four");
		numbers.put(985,"nine hundred eighty five");
		numbers.put(986,"nine hundred eighty six");
		numbers.put(987,"nine hundred eighty seven");
		numbers.put(988,"nine hundred eighty eight");
		numbers.put(989,"nine hundred eighty nine");
		numbers.put(990,"nine hundred ninety");
		numbers.put(991,"nine hundred ninety one");
		numbers.put(992,"nine hundred ninety two");
		numbers.put(993,"nine hundred ninety three");
		numbers.put(994,"nine hundred ninety four");
		numbers.put(995,"nine hundred ninety five");
		numbers.put(996,"nine hundred ninety six");
		numbers.put(997,"nine hundred ninety seven");
		numbers.put(998,"nine hundred ninety eight");
		numbers.put(999,"nine hundred ninety nine");
		return numbers;
	}
	
	@Test
	public void testValidNumbers() {
		try {
			 Map<Integer,String> input = setup();
			for (Integer number : input.keySet()) {
				String output=ConvertNumber.getNumberToWord(number).trim();
				assertTrue(input.get(number).trim().equalsIgnoreCase(output));
			}

		} catch (Exception e) {
			fail(e.getMessage());
		}

	}
	
	@Test
	public void testInvalidInputPositiveNumbers() {
		try {
			ConvertNumber.getNumberToWord(1000);
			fail("Exception was expected");
		}catch(Exception e) {
			assertTrue("Number cannot be converted".equals(e.getMessage()));
		}
	}
	
	@Test
	public void testInvalidInputNegativeNumbers() {
		try {
			ConvertNumber.getNumberToWord(-1);
			fail("Exception was expected");
		}catch(Exception e) {
			assertTrue("Number cannot be converted".equals(e.getMessage()));
		}
	}
}
